---
title: "Data"
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(ggrepel)
library(Rtsne)
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(5, `KDA Ratio`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`KDA Ratio`), y = `KDA Ratio`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by KDA Ratio for Each Role",
       x = "Hero",
       y = "KDA Ratio") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(5, `Win Rate, %`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`Win Rate, %`), y = `Win Rate, %`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by Win Rate for Each Role",
       x = "Hero",
       y = "Win Rate by Percentage") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(5, `Eliminations / 10min`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`Eliminations / 10min`), y = `Eliminations / 10min`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by Eliminations per 10 Minutes for Each Role",
       x = "Hero",
       y = "Eliminations per 10 Minutes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(5, `Damage / 10min`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`Damage / 10min`), y = `Damage / 10min`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by Damage per 10 Minutes for Each Role",
       x = "Hero",
       y = "Damage per 10 Minutes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(5, `Healing / 10min`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`Healing / 10min`), y = `Healing / 10min`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by Healing per 10 Minutes for Each Role",
       x = "Hero",
       y = "Healing per 10 Minutes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#| echo: false
#| message: false
data <- read_csv("data/ow_data.csv")

# Filter and select relevant data
filtered_data <- data %>%
  filter(`Skill Tier` == "All") %>%
  select(Hero, Role, `KDA Ratio`, `Pick Rate, %`, `Win Rate, %`, `Eliminations / 10min`, `Damage / 10min`, `Healing / 10min`, `Deaths / 10min`)

# Get the top 5 heroes by KDA Ratio for each role
top_heroes <- filtered_data %>%
  group_by(Role) %>%
  top_n(-5, `Deaths / 10min`)

# Create separate bar charts for each role
ggplot(top_heroes, aes(x = reorder(Hero, -`Deaths / 10min`), y = `Deaths / 10min`, fill = Hero)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Role, scales = "free") +  # Create separate charts for each role
  labs(title = "Top 5 Heroes by Deaths per 10 Minutes for Each Role",
       x = "Hero",
       y = "Deaths per 10 Minutes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

