---
title: "OWL Comparison"
---

There were two main compositions used in the Overwatch League during season 4.

The first composition was a dive composition that included Winston as the Tank, Sombra and Tracer as the Damage, and the support line was a mix of either Brigitte and Ana or Kiriko and Ana.

The second team composition was a rush composition that included Rammatra as the Tank, a mix of Mei and Sombra or Mei and Sojourn as the Damage line, and a mix of Ana Brigitte or Ana Lucio for the Support Line.

According to the collected data the Tank that performed the best was Junker Queen being in the top 5 for every category and being first in 3 of the categories.

The two best performing Damage characters were Soldier 76 and Torbjorn with these two characters being the only two damage characters to be in the top 5 in 4 different catagories

The two best performing Support Characters were Moira andd Zenyatta with Moira being the only support being in the top 5 six times and zenyatta five times along with baptiste, but baptiste had worse overall ratings in each top 5.

Overall the best team composition for Season 4 according to the data is Junker Queen for tank, Soldier 76 and Torbjorn for Damage, and Moira and Zenyatta for support.

This is very different from what was played in Overwatch League however, and this is because many of the characters that had good statistics are characters that are easy to play and get value for each statistic very easily, however the characters used in pro play are much harder to use, but once mastered give much more value than the easier to play characters.
